/*
 * Metabase
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package metabase

type DatabaseDetails struct {
	Host                     string `json:"host,omitempty"`
	Port                     int32  `json:"port,omitempty"`
	Dbname                   string `json:"dbname,omitempty"`
	AuthMech                 int32  `json:"authMech,omitempty"`
	User                     string `json:"user,omitempty"`
	Password                 string `json:"password,omitempty"`
	ConnProperties           string `json:"connProperties,omitempty"`
	LetUserControlScheduling bool   `json:"let-user-control-scheduling,omitempty"`
}
