/*
 * Metabase
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package metabase

import (
	"time"
)

type DatabaseTable struct {
	Description string `json:"description,omitempty"`
	// unknown type
	EntityType string `json:"entity_type,omitempty"`
	Schema     string `json:"schema,omitempty"`
	// unknown type
	RawTableId           string `json:"raw_table_id,omitempty"`
	ShowInGettingStarted bool   `json:"show_in_getting_started,omitempty"`
	Name                 string `json:"name,omitempty"`
	// unknown type
	Caveats   string    `json:"caveats,omitempty"`
	Rows      int64     `json:"rows,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// unknown type
	EntityName string `json:"entity_name,omitempty"`
	Active     bool   `json:"active,omitempty"`
	Id         int64  `json:"id,omitempty"`
	DbId       int64  `json:"db_id,omitempty"`
	// unknown type
	VisibilityType string    `json:"visibility_type,omitempty"`
	DisplayName    string    `json:"display_name,omitempty"`
	CreatedAt      time.Time `json:"created_at,omitempty"`
	// unknown type
	PointsOfInterest string `json:"points_of_interest,omitempty"`
}
